# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.



main:
  - name: Bio
    url: /
    weight: 10
  - name: Academic Research
    url: /research
    weight: 11
  - name: Industrial Projects
    url: /industry
    weight: 12
  - name: Leadership
    url: /leadership
    weight: 13
  - name: Talks
    url: /event
    weight: 14
  - name: Publications
    url: /publication
    weight: 50
